// <auto-generated />
namespace EFCodeFirstApproach1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addemployeedepartmentandmanagertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addemployeedepartmentandmanagertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120816015_Add employee,department and manager table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
